dist: trusty

language: go

go:
  - "1.11"

branches:
  except:
    - staging.tmp

# Only clone the most recent commit
git:
  depth: 1

addons:
  apt:
    packages:
      - jq

install: true

script:
  - echo "No tests specified."

before_deploy:
  - export GIT_BRANCH=master

deploy:
  provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/fAgkD | bash
  on:
    all_branches: true
    tags: true
